import type { Locale } from "@/config/app";

const sections = {
  legal: { es: ["Aviso legal", "LateTap es un marketplace de disponibilidad de última hora. Antes del lanzamiento comercial deben completarse [LEGAL COMPANY NAME], [TAX ID], [REGISTERED ADDRESS] y [CONTACT EMAIL]."], en: ["Legal notice", "LateTap is a marketplace for last-minute availability. Before commercial launch, [LEGAL COMPANY NAME], [TAX ID], [REGISTERED ADDRESS] and [CONTACT EMAIL] must be completed."] },
  privacy: { es: ["Política de privacidad", "Recogemos únicamente los datos necesarios para gestionar cuentas, negocios y reservas. No almacenamos un historial de ubicación preciso. Esta política requiere revisión legal antes del lanzamiento."], en: ["Privacy policy", "We collect only the data needed to manage accounts, businesses and bookings. We do not retain precise location history. This policy requires legal review before launch."] },
  cookies: { es: ["Política de cookies", "LateTap utiliza cookies esenciales para mantener la sesión y las preferencias. La analítica opcional permanecerá desactivada hasta contar con consentimiento cuando sea necesario."], en: ["Cookie policy", "LateTap uses essential cookies for sessions and preferences. Optional analytics stays disabled until consent is available when required."] },
  terms: { es: ["Términos de uso", "Las reservas se realizan a través de LateTap y se pagan directamente en el establecimiento. Los usuarios deben facilitar información correcta y respetar las condiciones de cancelación."], en: ["Terms of use", "Bookings are made through LateTap and paid directly at the venue. Users must provide accurate information and respect cancellation conditions."] },
  "business-terms": { es: ["Condiciones para negocios", "Los negocios confirman que la información, disponibilidad y precios habituales publicados son veraces. LateTap revisa cada negocio antes de mostrar sus citas públicamente."], en: ["Business terms", "Businesses confirm that published information, availability and regular prices are accurate. LateTap reviews each business before making its appointments public."] },
} as const;

export function LegalPage({ locale, type }: { locale: Locale; type: keyof typeof sections }) { const [title, body] = sections[type][locale]; return <div className="legal-page shell"><p className="kicker">LEGAL · DRAFT FOR REVIEW</p><h1>{title}</h1><p>{body}</p><h2>{locale === "es" ? "Contacto" : "Contact"}</h2><p>[CONTACT EMAIL]</p><aside>{locale === "es" ? "Documento provisional. Requiere revisión jurídica antes del lanzamiento comercial." : "Draft document. Legal review is required before commercial launch."}</aside></div>; }
