"use client";

import { useCallback, useEffect, useState } from "react";

import type { Locale } from "@/config/app";

type BusinessItem = { id: string; name: string; status: string; primaryCategoryId: string; email: string };
type Report = { id: string; entityType: string; entityId: string; reason: string; status: string };
type Category = { id: string; labelEs: string; labelEn: string; enabled: boolean; order: number };

export function AdminBusinesses({ locale }: { locale: Locale }) {
  const [items, setItems] = useState<BusinessItem[]>([]); const [reports, setReports] = useState<Report[]>([]); const [categories, setCategories] = useState<Category[]>([]); const [error, setError] = useState<string>();
  const load = useCallback(() => Promise.all([fetch("/api/v1/admin/businesses"), fetch("/api/v1/admin/reports"), fetch("/api/v1/admin/categories")]).then(async ([businessResponse, reportResponse, categoryResponse]) => {
    if (!businessResponse.ok) throw new Error((await businessResponse.json()).error?.message);
    const [businessPayload, reportPayload, categoryPayload] = await Promise.all([businessResponse.json(), reportResponse.ok ? reportResponse.json() : null, categoryResponse.ok ? categoryResponse.json() : null]);
    setItems(businessPayload.data.items); setReports(reportPayload?.data.items ?? []); setCategories(categoryPayload?.data.items ?? []);
  }).catch((cause: unknown) => setError(cause instanceof Error ? cause.message : "Error")), []);
  useEffect(() => { void load(); }, [load]);
  const moderate = async (id: string, action: string) => { const reason = action === "reject" ? prompt(locale === "es" ? "Motivo del rechazo" : "Rejection reason") : undefined; if (action === "reject" && !reason) return; const response = await fetch(`/api/v1/admin/businesses/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ action, reason }) }); if (!response.ok) setError((await response.json()).error?.message); else void load(); };
  const resolveReport = async (id: string, status: "resolved" | "dismissed") => { const response = await fetch(`/api/v1/admin/reports/${id}`, { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ status }) }); if (!response.ok) setError((await response.json()).error?.message); else void load(); };
  const toggleCategory = async (item: Category) => { const response = await fetch("/api/v1/admin/categories", { method: "PATCH", headers: { "content-type": "application/json" }, body: JSON.stringify({ id: item.id, enabled: !item.enabled }) }); if (!response.ok) setError((await response.json()).error?.message); else void load(); };
  return <div>{error && <p className="form-error">{error}</p>}<div className="admin-metrics"><article><span>{locale === "es" ? "Pendientes" : "Pending"}</span><strong>{items.filter((item) => item.status === "pending_review").length}</strong></article><article><span>{locale === "es" ? "Activos" : "Active"}</span><strong>{items.filter((item) => item.status === "approved").length}</strong></article><article><span>{locale === "es" ? "Reportes abiertos" : "Open reports"}</span><strong>{reports.filter((item) => item.status === "open").length}</strong></article><article><span>{locale === "es" ? "Categorías" : "Categories"}</span><strong>{categories.filter((item) => item.enabled).length}</strong></article></div>
    <h2>{locale === "es" ? "Negocios" : "Businesses"}</h2><div className="admin-table"><div className="admin-table-head"><span>{locale === "es" ? "Negocio" : "Business"}</span><span>{locale === "es" ? "Categoría" : "Category"}</span><span>Status</span><span>{locale === "es" ? "Acciones" : "Actions"}</span></div>{items.map((item) => <article key={item.id}><span><strong>{item.name}</strong><small>{item.email}</small></span><span>{item.primaryCategoryId}</span><span className={`status-badge ${item.status}`}>{item.status}</span><span className="admin-actions">{item.status === "pending_review" && <><button onClick={() => moderate(item.id, "approve")}>{locale === "es" ? "Aprobar" : "Approve"}</button><button onClick={() => moderate(item.id, "reject")}>{locale === "es" ? "Rechazar" : "Reject"}</button></>}{item.status === "approved" && <button onClick={() => moderate(item.id, "suspend")}>{locale === "es" ? "Suspender" : "Suspend"}</button>}{(item.status === "suspended" || item.status === "rejected") && <button onClick={() => moderate(item.id, "restore")}>{locale === "es" ? "Restaurar" : "Restore"}</button>}</span></article>)}</div>
    <div className="admin-split"><section><h2>{locale === "es" ? "Reportes" : "Reports"}</h2><div className="management-list">{reports.map((item) => <article key={item.id}><div><strong>{item.reason}</strong><span>{item.entityType} · {item.entityId}</span></div><span className="status-badge">{item.status}</span>{item.status === "open" && <span className="row-actions"><button onClick={() => resolveReport(item.id, "resolved")}>{locale === "es" ? "Resolver" : "Resolve"}</button><button onClick={() => resolveReport(item.id, "dismissed")}>{locale === "es" ? "Descartar" : "Dismiss"}</button></span>}</article>)}</div></section><section><h2>{locale === "es" ? "Categorías" : "Categories"}</h2><div className="management-list">{categories.map((item) => <article key={item.id}><div><strong>{locale === "es" ? item.labelEs : item.labelEn}</strong><span>{item.id}</span></div><span className="status-badge">{item.enabled ? "Active" : "Disabled"}</span><button onClick={() => toggleCategory(item)}>{item.enabled ? (locale === "es" ? "Desactivar" : "Disable") : (locale === "es" ? "Activar" : "Enable")}</button></article>)}</div></section></div>
  </div>;
}
