"use client";

import Link from "next/link";
import { useEffect, useState } from "react";

import type { Locale } from "@/config/app";
import type { Slot } from "@/types/domain";

export function BusinessOverview({ locale }: { locale: Locale }) { const [slots, setSlots] = useState<Slot[]>([]); const [error, setError] = useState(false); useEffect(() => { fetch("/api/v1/business/slots").then(async (response) => { if (!response.ok) throw new Error(); setSlots((await response.json()).data.items); }).catch(() => setError(true)); }, []); const published = slots.filter((item) => item.status === "published").length; const reserved = slots.filter((item) => item.status === "reserved").length; const completed = slots.filter((item) => item.status === "completed"); const revenue = completed.reduce((sum, item) => sum + item.priceCents, 0); return <div><header className="dashboard-heading"><p className="kicker">{locale === "es" ? "HOY" : "TODAY"}</p><h1>{locale === "es" ? "Tu negocio, de un vistazo" : "Your business at a glance"}</h1></header>{error ? <div className="dashboard-notice"><h3>{locale === "es" ? "Configura Firebase para activar el panel" : "Configure Firebase to activate the dashboard"}</h3><Link href={`/${locale}/business-onboarding`}>{locale === "es" ? "Registrar mi negocio" : "Register my business"}</Link></div> : <div className="stats-grid"><article><span>{locale === "es" ? "Publicadas" : "Published"}</span><strong>{published}</strong></article><article><span>{locale === "es" ? "Reservadas" : "Booked"}</span><strong>{reserved}</strong></article><article><span>{locale === "es" ? "Completadas" : "Completed"}</span><strong>{completed.length}</strong></article><article className="accent"><span>{locale === "es" ? "Ingresos recuperados" : "Recovered revenue"}</span><strong>{new Intl.NumberFormat(locale === "es" ? "es-ES" : "en-GB", { style: "currency", currency: "EUR", maximumFractionDigits: 0 }).format(revenue / 100)}</strong></article></div>}<Link className="quick-add" href={`/${locale}/business-dashboard/slots/new`}>+ {locale === "es" ? "Publicar una cita" : "Add a slot"}</Link></div>; }
