"use client";

import { Check, Zap } from "lucide-react";
import { useEffect, useState } from "react";
import { useForm, useWatch } from "react-hook-form";

import type { Locale } from "@/config/app";

type ServiceItem = { id: string; nameEs: string; nameEn?: string; regularPriceCents: number; durationMinutes: number };
type Form = { serviceId: string; date: string; time: string; durationMinutes: number; regularPrice: number; price: number; note: string };
export function SlotForm({ locale }: { locale: Locale }) { const [services, setServices] = useState<ServiceItem[]>([]); const [status, setStatus] = useState<{ id?: string; error?: string }>(); const { register, handleSubmit, control, setValue, formState: { isSubmitting } } = useForm<Form>({ defaultValues: { date: new Date().toISOString().slice(0,10), durationMinutes: 45, time: "17:30" } }); useEffect(() => { fetch("/api/v1/business/services").then((response) => response.json()).then((payload) => setServices(payload.data?.items ?? [])).catch(() => setServices([])); }, []); const regular = Number(useWatch({ control, name: "regularPrice" }) || 0); const price = Number(useWatch({ control, name: "price" }) || 0); const discount = regular > 0 && price > 0 ? Math.round((1 - price / regular) * 100) : 0; const chooseService = (id: string) => { const service = services.find((item) => item.id === id); if (service) { setValue("regularPrice", service.regularPriceCents / 100); setValue("price", Math.round(service.regularPriceCents * .8) / 100); setValue("durationMinutes", service.durationMinutes); } }; const submit = async (data: Form) => { const startAt = new Date(`${data.date}T${data.time}:00`).toISOString(); const response = await fetch("/api/v1/business/slots", { method: "POST", headers: { "content-type": "application/json" }, body: JSON.stringify({ serviceId: data.serviceId, startAt, durationMinutes: Number(data.durationMinutes), regularPriceCents: Math.round(Number(data.regularPrice) * 100), priceCents: Math.round(Number(data.price) * 100), note: data.note }) }); const payload = await response.json(); setStatus(response.ok ? { id: payload.data.id } : { error: payload.error?.message ?? "Error" }); };
  if (status?.id) return <div className="onboarding-success"><span><Check /></span><h1>{locale === "es" ? "Cita publicada" : "Slot published"}</h1><p>{locale === "es" ? "Ya puede encontrarla gente cerca de ti." : "People nearby can now find it."}</p><button onClick={() => location.reload()}>{locale === "es" ? "Publicar otra" : "Publish another"}</button></div>;
  return <form className="slot-form" onSubmit={handleSubmit(submit)}><header><p className="kicker"><Zap size={13} /> QUICK PUBLISH</p><h1>{locale === "es" ? "Publicar una cita" : "Add a slot"}</h1><p>{locale === "es" ? "Una cancelación convertida en oportunidad, en segundos." : "Turn a cancellation into an opportunity in seconds."}</p></header><label>{locale === "es" ? "Servicio" : "Service"}<select {...register("serviceId", { required: true })} onChange={(event) => { register("serviceId").onChange(event); chooseService(event.target.value); }}><option value="">—</option>{services.map((service) => <option value={service.id} key={service.id}>{locale === "en" && service.nameEn ? service.nameEn : service.nameEs}</option>)}</select></label><div className="form-grid"><label>{locale === "es" ? "Fecha" : "Date"}<input type="date" {...register("date", { required: true })} /></label><label>{locale === "es" ? "Hora" : "Time"}<input type="time" {...register("time", { required: true })} /></label><label>{locale === "es" ? "Duración" : "Duration"}<select {...register("durationMinutes", { valueAsNumber: true })}>{[15,30,45,60,75,90].map((value) => <option key={value} value={value}>{value} min</option>)}</select></label></div><div className="price-editor"><label>{locale === "es" ? "Precio habitual" : "Regular price"}<span><input type="number" step="0.01" {...register("regularPrice", { required: true, valueAsNumber: true })} />€</span></label><label>{locale === "es" ? "Precio LateTap" : "LateTap price"}<span><input type="number" step="0.01" {...register("price", { required: true, valueAsNumber: true })} />€</span></label><strong>{discount > 0 ? `−${discount}%` : "—"}</strong></div><div className="discount-presets">{[10,20,30].map((value) => <button type="button" key={value} onClick={() => setValue("price", Math.round(regular * (1 - value / 100) * 100) / 100)}>−{value}%</button>)}</div><label>{locale === "es" ? "Nota opcional" : "Optional note"}<textarea {...register("note")} /></label>{status?.error && <p className="form-error">{status.error}</p>}{services.length === 0 && <p className="config-note">{locale === "es" ? "Crea primero un servicio en el panel." : "Create a service in the dashboard first."}</p>}<button className="next-button" disabled={isSubmitting || services.length === 0}>{isSubmitting ? "..." : locale === "es" ? "Publicar ahora" : "Publish now"}</button></form>; }
